version: '3.8'
services:
  backend:
    image: sshindetech/vibe-backend:latest
    pull_policy: always
    container_name: vibe-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MODEL_ID=${MODEL_ID}
    volumes:
      - ./backend/database:/app/database

  frontend:
    image: sshindetech/vibe-frontend:latest
    pull_policy: always
    container_name: vibe-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
