# GitHub Actions workflow to build and push Docker images for frontend and backend
name: Build and Push Docker Images

on:
  push:
    branches: [ feature/microservices ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      IMAGE_NAME_GATEWAY: ${{ secrets.DOCKERHUB_USERNAME }}/vibe-gateway
      IMAGE_NAME_AI: ${{ secrets.DOCKERHUB_USERNAME }}/vibe-ai-service
      IMAGE_NAME_EXCEL: ${{ secrets.DOCKERHUB_USERNAME }}/vibe-excel-service
      IMAGE_NAME_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME }}/vibe-frontend
      EXPO_PUBLIC_API_URL: ${{ vars.EXPO_PUBLIC_API_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}


      - name: Build and push gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/gateway
          file: ./backend/gateway/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_GATEWAY }}:latest

      - name: Build and push ai-service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/ai-service
          file: ./backend/ai-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_AI }}:latest

      - name: Build and push excel-service image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/excel-service
          file: ./backend/excel-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_EXCEL }}:latest

      - name: Create .env file for frontend
        run: echo "EXPO_PUBLIC_API_URL=${{ env.EXPO_PUBLIC_API_URL }}" > frontend/.env

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_FRONTEND }}:latest
